server:
  port: 8084

spring:
  application:
    name: ms-interactions

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/heypudu?currentSchema=heypudu_interactions}
    username: ${DB_USERNAME:heypudu_interactions_user}
    password: ${DB_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: heypudu_interactions
    open-in-view: false
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: heypudu_interactions
    default-schema: heypudu_interactions

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
          jwk-set-uri: ${COGNITO_JWK_SET_URI}

clients:
  posts:
    base-url: ${CLIENTS_POSTS_BASE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    com.heypudu.ms_interactions: DEBUG
    org.springframework.security: INFO